//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointPnP.PowerShell.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePointPnP.PowerShell.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint PnP PowerShell Library.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete all items in the first and second stage recycle bins?.
        /// </summary>
        internal static string ClearBothRecycleBins {
            get {
                return ResourceManager.GetString("ClearBothRecycleBins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete file &apos;{0}&apos; from the recycle bin?.
        /// </summary>
        internal static string ClearRecycleBinItem {
            get {
                return ResourceManager.GetString("ClearRecycleBinItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete all the items in the second stage recycle bin?.
        /// </summary>
        internal static string ClearSecondStageRecycleBin {
            get {
                return ResourceManager.GetString("ClearSecondStageRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete the site collection previously located at &apos;{0}&apos; from the recycle bin?.
        /// </summary>
        internal static string ClearTenantRecycleBinItem {
            get {
                return ResourceManager.GetString("ClearTenantRecycleBinItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not executed due to healthscore value of {0}.
        /// </summary>
        internal static string CommandNotExecutedDueToHealthscoreValueOf0 {
            get {
                return ResourceManager.GetString("CommandNotExecutedDueToHealthscoreValueOf0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file &apos;{0}&apos; to &apos;{1}&apos;?.
        /// </summary>
        internal static string CopyFile0To1 {
            get {
                return ResourceManager.GetString("CopyFile0To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create site with url &apos;{0}&apos;?.
        /// </summary>
        internal static string CreateSiteWithUrl0 {
            get {
                return ResourceManager.GetString("CreateSiteWithUrl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current site is not a tenant administration site.
        /// </summary>
        internal static string CurrentSiteIsNoTenantAdminSite {
            get {
                return ResourceManager.GetString("CurrentSiteIsNoTenantAdminSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        internal static string Delete0 {
            get {
                return ResourceManager.GetString("Delete0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete field &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteField0 {
            get {
                return ResourceManager.GetString("DeleteField0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials.
        /// </summary>
        internal static string EnterYourCredentials {
            get {
                return ResourceManager.GetString("EnterYourCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} exists, overwrite?.
        /// </summary>
        internal static string File0ExistsOverwrite {
            get {
                return ResourceManager.GetString("File0ExistsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unified Group with MailNickname of {0} already exists. Do you want to create another one?.
        /// </summary>
        internal static string ForceCreationOfExistingGroup0 {
            get {
                return ResourceManager.GetString("ForceCreationOfExistingGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request can take a long time to execute. Continue?.
        /// </summary>
        internal static string GetTenantSite_ExecuteCmdlet_This_request_can_take_a_long_time_to_execute__Continue_ {
            get {
                return ResourceManager.GetString("GetTenantSite_ExecuteCmdlet_This_request_can_take_a_long_time_to_execute__Continu" +
                        "e_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health score not sufficient.
        /// </summary>
        internal static string HealthScoreNotSufficient {
            get {
                return ResourceManager.GetString("HealthScoreNotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List not found.
        /// </summary>
        internal static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Azure AD OAuth 2.0 Access Token has expired. Authenticate again using the Connect-PnPMicrosoftGraph cmdlet..
        /// </summary>
        internal static string MicrosoftGraphOAuthAccessTokenExpired {
            get {
                return ResourceManager.GetString("MicrosoftGraphOAuthAccessTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move file &apos;{0}&apos; to &apos;{1}&apos;?.
        /// </summary>
        internal static string MoveFile0To1 {
            get {
                return ResourceManager.GetString("MoveFile0To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all items from the first stage recycle bin to the second stage recycle bin?.
        /// </summary>
        internal static string MoveFirstStageRecycleBinItemsToSecondStage {
            get {
                return ResourceManager.GetString("MoveFirstStageRecycleBinItemsToSecondStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move list item with ID {0} to Recycle Bin?.
        /// </summary>
        internal static string MoveListItemWithId0ToRecycleBin {
            get {
                return ResourceManager.GetString("MoveListItemWithId0ToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move recycle bin item with leaf &apos;{0}&apos; to the second stage recycle bin?.
        /// </summary>
        internal static string MoveRecycleBinItemWithLeaf0ToSecondStage {
            get {
                return ResourceManager.GetString("MoveRecycleBinItemWithLeaf0ToSecondStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Azure AD connection, please connect first with Connect-PnPOnline -Graph, Connect-PnPOnline -Scopes or Connect-PnPOnline -AppId -AppSecret -AADDomain.
        /// </summary>
        internal static string NoAzureADAccessToken {
            get {
                return ResourceManager.GetString("NoAzureADAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection, please connect first with Connect-PnPOnline.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to disconnect.
        /// </summary>
        internal static string NoConnectionToDisconnect {
            get {
                return ResourceManager.GetString("NoConnectionToDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No context present. Connect first with Connect-PnPOnline.
        /// </summary>
        internal static string NoContextPresent {
            get {
                return ResourceManager.GetString("NoContextPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint PnP PowerShell Library ({0}).
        /// </summary>
        internal static string OfficeDevPnPPowerShellLibrary0 {
            get {
                return ResourceManager.GetString("OfficeDevPnPPowerShellLibrary0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Client-Side Page?.
        /// </summary>
        internal static string RemoveClientSidePage {
            get {
                return ResourceManager.GetString("RemoveClientSidePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove component with instance id &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveComponentWithInstanceId0 {
            get {
                return ResourceManager.GetString("RemoveComponentWithInstanceId0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove content type?.
        /// </summary>
        internal static string RemoveContentType {
            get {
                return ResourceManager.GetString("RemoveContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove custom action?.
        /// </summary>
        internal static string RemoveCustomAction {
            get {
                return ResourceManager.GetString("RemoveCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The classification &apos;{0}&apos; you are trying remove is currently set as the default classification. Do you want to remove this classification? It will also remove this as  the default classification.
        /// </summary>
        internal static string RemoveDefaultClassification0 {
            get {
                return ResourceManager.GetString("RemoveDefaultClassification0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove event receiver named &apos;{0}&apos; with id &apos;{1}&apos;?.
        /// </summary>
        internal static string RemoveEventReceiver {
            get {
                return ResourceManager.GetString("RemoveEventReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Group &apos;{0}&apos;.
        /// </summary>
        internal static string RemoveGroup0 {
            get {
                return ResourceManager.GetString("RemoveGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Image Rendition with name &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveImageRenditionWithName0 {
            get {
                return ResourceManager.GetString("RemoveImageRenditionWithName0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove JavaScript (&apos;{0}&apos;)?.
        /// </summary>
        internal static string RemoveJavaScript0 {
            get {
                return ResourceManager.GetString("RemoveJavaScript0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove key and value from property bag?.
        /// </summary>
        internal static string RemoveKeyAndValueFromPropertyBag {
            get {
                return ResourceManager.GetString("RemoveKeyAndValueFromPropertyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove list?.
        /// </summary>
        internal static string RemoveList {
            get {
                return ResourceManager.GetString("RemoveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove list item with ID {0}?.
        /// </summary>
        internal static string RemoveListItemWithId0 {
            get {
                return ResourceManager.GetString("RemoveListItemWithId0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Navigation Node &apos;{0}&apos;.
        /// </summary>
        internal static string RemoveNavigationNode0 {
            get {
                return ResourceManager.GetString("RemoveNavigationNode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Navigation Nodes in {0}?.
        /// </summary>
        internal static string RemoveNavigationNodeInLocation {
            get {
                return ResourceManager.GetString("RemoveNavigationNodeInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove propertybag value.
        /// </summary>
        internal static string RemovePropertyBagValue {
            get {
                return ResourceManager.GetString("RemovePropertyBagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove site collection &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveSiteCollection0 {
            get {
                return ResourceManager.GetString("RemoveSiteCollection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove site design?.
        /// </summary>
        internal static string RemoveSiteDesign {
            get {
                return ResourceManager.GetString("RemoveSiteDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove site script?.
        /// </summary>
        internal static string RemoveSiteScript {
            get {
                return ResourceManager.GetString("RemoveSiteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Term &apos;{0}&apos; and all underlying Terms?.
        /// </summary>
        internal static string RemoveTerm0AndAllUnderlyingTerms {
            get {
                return ResourceManager.GetString("RemoveTerm0AndAllUnderlyingTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Termgroup &apos;{0}&apos; and all underlying Termsets and Terms? .
        /// </summary>
        internal static string RemoveTermGroup0AndAllUnderlyingTermSetsAndTerms {
            get {
                return ResourceManager.GetString("RemoveTermGroup0AndAllUnderlyingTermSetsAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Termset &apos;{0}&apos; and it&apos;s underlying Terms?.
        /// </summary>
        internal static string RemoveTermSet0 {
            get {
                return ResourceManager.GetString("RemoveTermSet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the {0} key and its value from the property bag?.
        /// </summary>
        internal static string RemoveThe0KeyAndItsValueFromThePropertyBag {
            get {
                return ResourceManager.GetString("RemoveThe0KeyAndItsValueFromThePropertyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User with Id {0}, LoginName &apos;{1}&apos;, Email &apos;{2}&apos; from the User Information List?.
        /// </summary>
        internal static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove view &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveView0 {
            get {
                return ResourceManager.GetString("RemoveView0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Web &apos;{0}&apos; ? .
        /// </summary>
        internal static string RemoveWeb0 {
            get {
                return ResourceManager.GetString("RemoveWeb0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Webhook Subscription &apos;{0}&apos; from {1} &apos;{2}&apos; ?.
        /// </summary>
        internal static string RemoveWebhookSubscription0From1_2 {
            get {
                return ResourceManager.GetString("RemoveWebhookSubscription0From1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Web Part with title &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveWebPartWithTitle0 {
            get {
                return ResourceManager.GetString("RemoveWebPartWithTitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file &apos;{0}&apos; to &apos;{1}&apos;?.
        /// </summary>
        internal static string RenameFile0To1 {
            get {
                return ResourceManager.GetString("RenameFile0To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the site collection previously located at &apos;{0}&apos; from the recycle bin to its original location?.
        /// </summary>
        internal static string ResetTenantRecycleBinItem {
            get {
                return ResourceManager.GetString("ResetTenantRecycleBinItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the file &apos;{0}&apos; from the recycle bin to its original location?.
        /// </summary>
        internal static string RestoreRecycleBinItem {
            get {
                return ResourceManager.GetString("RestoreRecycleBinItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore all items from the first and second stage recycle bins to their original locations?.
        /// </summary>
        internal static string RestoreRecycleBinItems {
            get {
                return ResourceManager.GetString("RestoreRecycleBinItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry {0}: Server not healthy, waiting {1} seconds (Server Health Score: {2}).
        /// </summary>
        internal static string Retry0ServerNotHealthyWaiting1seconds {
            get {
                return ResourceManager.GetString("Retry0ServerNotHealthyWaiting1seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall app {0}?.
        /// </summary>
        internal static string UninstallApp0 {
            get {
                return ResourceManager.GetString("UninstallApp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web &apos;{0}&apos; created at {1}.
        /// </summary>
        internal static string Web0CreatedAt1 {
            get {
                return ResourceManager.GetString("Web0CreatedAt1", resourceCulture);
            }
        }
    }
}
