//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointPnP.PowerShell.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePointPnP.PowerShell.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Office Dev PnP PowerShell Library.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Command not executed due to healthscore value of {0}.
        /// </summary>
        internal static string CommandNotExecutedDueToHealthscoreValueOf0 {
            get {
                return ResourceManager.GetString("CommandNotExecutedDueToHealthscoreValueOf0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current site is not a tenant administration site.
        /// </summary>
        internal static string CurrentSiteIsNoTenantAdminSite {
            get {
                return ResourceManager.GetString("CurrentSiteIsNoTenantAdminSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete &apos;{0}&apos;?.
        /// </summary>
        internal static string Delete0 {
            get {
                return ResourceManager.GetString("Delete0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete field &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteField0 {
            get {
                return ResourceManager.GetString("DeleteField0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter your credentials.
        /// </summary>
        internal static string EnterYourCredentials {
            get {
                return ResourceManager.GetString("EnterYourCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File {0} exists, overwrite?.
        /// </summary>
        internal static string File0ExistsOverwrite {
            get {
                return ResourceManager.GetString("File0ExistsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File does not exist.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This request can take a long time to execute. Continue?.
        /// </summary>
        internal static string GetTenantSite_ExecuteCmdlet_This_request_can_take_a_long_time_to_execute__Continue_ {
            get {
                return ResourceManager.GetString("GetTenantSite_ExecuteCmdlet_This_request_can_take_a_long_time_to_execute__Continu" +
                        "e_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Health score not sufficient.
        /// </summary>
        internal static string HealthScoreNotSufficient {
            get {
                return ResourceManager.GetString("HealthScoreNotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List not found.
        /// </summary>
        internal static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No Azure AD connection, please connect first with Connect-PnPMicrosoftGraph.
        /// </summary>
        internal static string NoAzureADAccessToken {
            get {
                return ResourceManager.GetString("NoAzureADAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No connection, please connect first with Connect-SPOnline.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No connection to disconnect.
        /// </summary>
        internal static string NoConnectionToDisconnect {
            get {
                return ResourceManager.GetString("NoConnectionToDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No context present. Connect first with Connect-SPOnline.
        /// </summary>
        internal static string NoContextPresent {
            get {
                return ResourceManager.GetString("NoContextPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Office Dev PnP PowerShell Library ({0}).
        /// </summary>
        internal static string OfficeDevPnPPowerShellLibrary0 {
            get {
                return ResourceManager.GetString("OfficeDevPnPPowerShellLibrary0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        /// </summary>
        internal static System.Drawing.Icon pnp {
            get {
                object obj = ResourceManager.GetObject("pnp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove content type?.
        /// </summary>
        internal static string RemoveContentType {
            get {
                return ResourceManager.GetString("RemoveContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove custom action?.
        /// </summary>
        internal static string RemoveCustomAction {
            get {
                return ResourceManager.GetString("RemoveCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove event receiver?.
        /// </summary>
        internal static string RemoveEventReceiver {
            get {
                return ResourceManager.GetString("RemoveEventReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove Group &apos;{0}&apos;.
        /// </summary>
        internal static string RemoveGroup0 {
            get {
                return ResourceManager.GetString("RemoveGroup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove JavaScript (&apos;{0}&apos;)?.
        /// </summary>
        internal static string RemoveJavaScript0 {
            get {
                return ResourceManager.GetString("RemoveJavaScript0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove key and value from property bag?.
        /// </summary>
        internal static string RemoveKeyAndValueFromPropertyBag {
            get {
                return ResourceManager.GetString("RemoveKeyAndValueFromPropertyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove list?.
        /// </summary>
        internal static string RemoveList {
            get {
                return ResourceManager.GetString("RemoveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove list item with ID {0}?.
        /// </summary>
        internal static string RemoveListItemWithId0 {
            get {
                return ResourceManager.GetString("RemoveListItemWithId0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove Navigation Node &apos;{0}&apos;.
        /// </summary>
        internal static string RemoveNavigationNode0 {
            get {
                return ResourceManager.GetString("RemoveNavigationNode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove propertybag value.
        /// </summary>
        internal static string RemovePropertyBagValue {
            get {
                return ResourceManager.GetString("RemovePropertyBagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove site collection &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveSiteCollection0 {
            get {
                return ResourceManager.GetString("RemoveSiteCollection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove Term &apos;{0}&apos; and all underlying Terms?.
        /// </summary>
        internal static string RemoveTerm0AndAllUnderlyingTerms {
            get {
                return ResourceManager.GetString("RemoveTerm0AndAllUnderlyingTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove Termgroup &apos;{0}&apos; and all underlying Termsets and Terms? .
        /// </summary>
        internal static string RemoveTermGroup0AndAllUnderlyingTermSetsAndTerms {
            get {
                return ResourceManager.GetString("RemoveTermGroup0AndAllUnderlyingTermSetsAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove Termset &apos;{0}&apos; and it&apos;s underlying Terms?.
        /// </summary>
        internal static string RemoveTermSet0 {
            get {
                return ResourceManager.GetString("RemoveTermSet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove the {0} key and its value from the property bag?.
        /// </summary>
        internal static string RemoveThe0KeyAndItsValueFromThePropertyBag {
            get {
                return ResourceManager.GetString("RemoveThe0KeyAndItsValueFromThePropertyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove view &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveView0 {
            get {
                return ResourceManager.GetString("RemoveView0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove Web &apos;{0}&apos; ? .
        /// </summary>
        internal static string RemoveWeb0 {
            get {
                return ResourceManager.GetString("RemoveWeb0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Retry {0}: Server not healthy, waiting {1} seconds (Server Health Score: {2}).
        /// </summary>
        internal static string Retry0ServerNotHealthyWaiting1seconds {
            get {
                return ResourceManager.GetString("Retry0ServerNotHealthyWaiting1seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uninstall app {0}?.
        /// </summary>
        internal static string UninstallApp0 {
            get {
                return ResourceManager.GetString("UninstallApp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web &apos;{0}&apos; created at {1}.
        /// </summary>
        internal static string Web0CreatedAt1 {
            get {
                return ResourceManager.GetString("Web0CreatedAt1", resourceCulture);
            }
        }
    }
}
